### ISSUE TITLE
acs14 function sending Error in open.connection(con, "rb") : HTTP error 404.

### ISSUE THREAD

**Issue by rafaelcachoaguirre** [walkerke/acs14lite#3]
I am trying to reproduce a shiny app:
[https://gist.github.com/walkerke/6915b02ac7f0c215bc2c75a687b3d269](url)

One of the lines use the acs14 function with the following inputs:
inc <- acs14(geography = 'tract', variable = 'B19013_001E', state = 'TX', county = 'Travis')

Whe I run the function I hot the following error:
**Error in open.connection(con, "rb") : HTTP error 404.**

I am uisng the API key for cencus.

Any clue why this error is arising?

**Comment by walkerke** [comment]
This package is very old and no longer works as the Census API endpoints have changed.  I suggest you check out its modern successor, tidycensus: https://github.com/walkerke/tidycensus
